apiVersion: v1
kind: Secret
metadata:
  name: murmur-secrets
  namespace: murmur
  labels:
    app.kubernetes.io/name: murmur
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: murmur-stack
type: Opaque
stringData:
  APP_KEY: "base64:9+4sOlPV405wn5OQexEonPAT6mtQa9GaZh5ppHFj82c="
  PUSHER_APP_SECRET: "murmur-secret"